### ISSUE TITLE
Let's add an animated logo

### ISSUE THREAD

**Issue by labofoz** [labofoz/labofoz-twentysixteen#1]
## Scope
- [x] I have an SVG that looks like this (notice mouth):
![image](https://user-images.githubusercontent.com/52610021/60844211-79f3eb00-a18d-11e9-890d-b8339978e7fe.png)
---
- [x] It's animated similarly to this (see: https://github.com/labofoz/labofoz-nuxt-twitter):
![ezgif-4-7157ce66f7e6](https://user-images.githubusercontent.com/52610021/60844243-9001ab80-a18d-11e9-90b4-5bff2f101715.gif)
---
- [x] It's injected via the WordPress methods

## Tasks
- [x] Start a simple Parcel environment
- [x] Create an SVG with the "ooo" face
- [x] Create a 2016 child theme
- [x] Inject our animated logo
- [x] Remove custom logo option from customizer

**Comment by labofoz** [comment]
Check it out!

![ezgif-4-10425f8c65fa](https://user-images.githubusercontent.com/52610021/60927794-fd7e0c80-a25f-11e9-96c1-0df841872cf8.gif)
